In [1]:
import pandas as pd
import numpy as np

In [103]:
pd.set_option('display.float_format',
      lambda x: '{:,.4f}'.format(x) if abs(x) >0.01 else '{:,.3e}'.format(x))

In [110]:
# model1
data4 = {
    "Metrics": ["1SD Coverage", "2SD Coverage", "3SD Coverage", "Mean of SD", "MAE", "MSE", "R^2"],
    "MSFT": [0.7843137254901961,0.9803921568627451,1.0,0.5617052785847774,0.0009049355456446909,1.3059909984720701e-06,-0.08065558511353998],
    "MRNA": [0.5882352941176471,0.9215686274509803,0.9803921568627451,1.3006477210391914,0.0024193510690941034,2.082611952514644e-05,0.07010012235065244],
    "SPLK": [0.6862745098039216,0.9019607843137255,0.9803921568627451,0.25247660604559446, 0.0011101139175463235,1.8510606952292412e-06,-0.047878689432542254]
}

table1 = pd.DataFrame(data1, index=None)
table1

        Metrics      MSFT      MRNA      SPLK
0  1SD Coverage    0.7843    0.5882    0.6863
1  2SD Coverage    0.9804    0.9216    0.9020
2  3SD Coverage    1.0000    0.9804    0.9804
3    Mean of SD    0.5617    1.3006    0.2525
4           MAE 9.049e-04 2.419e-03 1.110e-03
5           MSE 1.306e-06 2.083e-05 1.851e-06
6           R^2   -0.0807    0.0701   -0.0479

In [104]:
# model2
data2 = {
    "Metrics": ["1SD Coverage", "2SD Coverage", "3SD Coverage", "Mean of SD", "MAE", "MSE", "R^2"],
    "MSFT": [0.6129, 0.9032, 0.9677, 0.4200, 0.0008738731445854007,1.283049454611973e-06, -0.06167237042634377],
    "MRNA": [0.7096774193548387,0.967741935483871,1.0,1.8643063875057462,0.002213251426395608,8.229315639573659e-06,-0.5120352343138708],
    "SPLK": [0.7096774193548387,0.9354838709677419,0.967741935483871,0.24035089130097548,0.0009833858533677981,1.481088585622057e-06,-0.08130478591592949]
}

table2 = pd.DataFrame(data2, index=None)
table2

        Metrics      MSFT      MRNA      SPLK
0  1SD Coverage    0.6129    0.7097    0.7097
1  2SD Coverage    0.9032    0.9677    0.9355
2  3SD Coverage    0.9677    1.0000    0.9677
3    Mean of SD    0.4200    1.8643    0.2404
4           MAE 8.739e-04 2.213e-03 9.834e-04
5           MSE 1.283e-06 8.229e-06 1.481e-06
6           R^2   -0.0617   -0.5120   -0.0813

In [116]:
# model3
data3 = {
    "Metrics": ["1SD Coverage", "2SD Coverage", "3SD Coverage", "Mean of SD", "MAE", "MSE", "R^2"],
    "MSFT": [0.6451612903225806,0.9032258064516129,0.967741935483871,0.4183512446423727,0.0008719683302811819,1.2807855001601693e-06,-0.059799038201507004],
    "MRNA": [0.6129032258064516,0.9354838709677419,1.0,1.7744052806248798,0.00215922822993348,7.672119809201741e-06,-0.40965737388965184],
    "SPLK": [0.6774193548387096,0.9354838709677419,0.9354838709677419,0.23784129214845778,0.0009867489153307693,1.5515266780971205e-06,-0.13272983046995623]
}

table3 = pd.DataFrame(data3, index=None)
table3

        Metrics      MSFT      MRNA      SPLK
0  1SD Coverage    0.6452    0.6129    0.6774
1  2SD Coverage    0.9032    0.9355    0.9355
2  3SD Coverage    0.9677    1.0000    0.9355
3    Mean of SD    0.4184    1.7744    0.2378
4           MAE 8.720e-04 2.159e-03 9.867e-04
5           MSE 1.281e-06 7.672e-06 1.552e-06
6           R^2   -0.0598   -0.4097   -0.1327

In [117]:
# model4
data4 = {
    "Metrics": ["1SD Coverage", "2SD Coverage", "3SD Coverage", "Mean of SD", "MAE", "MSE", "R^2"],
    "MSFT": [0.6451612903225806,0.9032258064516129,0.967741935483871,0.4160882077311902,0.0008794377379942906,1.31448816277177e-06,-0.0876866504645577],
    "MRNA": [0.5806451612903226,0.967741935483871,1.0,1.7821572953537839,0.002159091702684195,7.382410641399386e-06,-0.3564268880744783],
    "SPLK": [0.6774193548387096,0.9354838709677419,0.9354838709677419,0.2403789906472426,0.0009987683428151234,1.5897701817577325e-06,-0.16065043153315672]
}

table4 = pd.DataFrame(data4, index=None)
table4

        Metrics      MSFT      MRNA      SPLK
0  1SD Coverage    0.6452    0.5806    0.6774
1  2SD Coverage    0.9032    0.9677    0.9355
2  3SD Coverage    0.9677    1.0000    0.9355
3    Mean of SD    0.4161    1.7822    0.2404
4           MAE 8.794e-04 2.159e-03 9.988e-04
5           MSE 1.314e-06 7.382e-06 1.590e-06
6           R^2   -0.0877   -0.3564   -0.1607

### MSFT without beta
0.6129032258064516,
0.9032258064516129,
0.967741935483871,
0.4200,
0.0008738731445854007,
1.283049454611973e-06,
-0.06167237042634377

-------------------------------------

0.6129032258064516,
0.9032258064516129,
0.967741935483871,
0.4178021497610706,
0.0008719960723094876,
1.2817470370241868e-06,
-0.06059467169638455

-------------------------------------

0.6451612903225806,
0.9032258064516129,
0.967741935483871,
0.4175334109995014,
0.000879514323596926,
1.3117324656247929e-06,
-0.08540642072618554

-------------------------------------

0.7843137254901961,
0.9803921568627451,
1.0,
0.5617052785847774,
0.0009049355456446909,
1.3059909984720701e-06,
-0.08065558511353998

In [ ]:
### MSFT 
0.6129032258064516,
0.9032258064516129,
0.967741935483871,
0.4200,
0.0008738731445854007,
1.283049454611973e-06,
-0.06167237042634377

-------------------------------------

0.6451612903225806,
0.9032258064516129,
0.967741935483871,
0.4183512446423727,
0.0008719683302811819,
1.2807855001601693e-06,
-0.059799038201507004

-------------------------------------

0.6451612903225806,
0.9032258064516129,
0.967741935483871,
0.4160882077311902,
0.0008794377379942906,
1.31448816277177e-06,
-0.0876866504645577

-------------------------------------

0.7843137254901961,
0.9803921568627451,
1.0,
0.5617052785847774,
0.0009049355456446909,
1.3059909984720701e-06,
-0.08065558511353998

### MRNA without beta
0.7096774193548387,
0.967741935483871,
1.0,
1.8643063875057462,
0.002213251426395608,
8.229315639573659e-06,
-0.5120352343138708

-------------------------------------

0.6129032258064516,
0.9354838709677419,
1.0,
1.7764739589297829,
0.002120100018390953,
7.56325938817681e-06,
-0.3896556143969918

-------------------------------------

0.5806451612903226,
0.967741935483871,
1.0,
1.7833154757218403,
0.0021388722284176455,
7.324770711936304e-06,
-0.3458362620651372

-------------------------------------

0.5882352941176471,
0.9215686274509803,
0.9803921568627451,
1.3006477210391914,
0.0024193510690941034,
2.082611952514644e-05,
0.07010012235065244

In [ ]:
### MRNA
0.7096774193548387,
0.967741935483871,
1.0,
1.8643063875057462,
0.002213251426395608,
8.229315639573659e-06,
-0.5120352343138708

-------------------------------------

0.6129032258064516,
0.9354838709677419,
1.0,
1.7744052806248798,
0.00215922822993348,
7.672119809201741e-06,
-0.40965737388965184

-------------------------------------

0.5806451612903226,
0.967741935483871,
1.0,
1.7821572953537839,
0.002159091702684195,
7.382410641399386e-06,
-0.3564268880744783

-------------------------------------

0.5882352941176471,
0.9215686274509803,
0.9803921568627451,
1.3006477210391914,
0.0024193510690941034,
2.082611952514644e-05,
0.07010012235065244

### SPLK without beta 
0.7096774193548387,
0.9354838709677419,
0.967741935483871,
0.24035089130097548,
0.0009833858533677981,
1.481088585622057e-06,
-0.08130478591592949

-------------------------------------

0.7096774193548387,
0.9354838709677419,
1.0,
0.23820625777043808,
0.000973679767681888,
1.4783456694700746e-06,
-0.07930225319013773

-------------------------------------

0.7096774193548387,
0.9354838709677419,
0.967741935483871,
0.2409559753277231,
0.0009949820400821769,
1.5441487169287658e-06,
-0.12734337026825737

-------------------------------------

0.6862745098039216,
0.9019607843137255,
0.9803921568627451,
0.25247660604559446, 
0.0011101139175463235,
1.8510606952292412e-06,
-0.047878689432542254

In [ ]:
### SPLK
0.7096774193548387,
0.9354838709677419,
0.967741935483871,
0.24035089130097548,
0.0009833858533677981,
1.481088585622057e-06,
-0.08130478591592949

-------------------------------------

0.6774193548387096,
0.9354838709677419,
0.9354838709677419,
0.23784129214845778,
0.0009867489153307693,
1.5515266780971205e-06,
-0.13272983046995623

-------------------------------------

0.6774193548387096,
0.9354838709677419,
0.9354838709677419,
0.2403789906472426,
0.0009987683428151234,
1.5897701817577325e-06,
-0.16065043153315672

-------------------------------------

0.6862745098039216,
0.9019607843137255,
0.9803921568627451,
0.25247660604559446, 
0.0011101139175463235,
1.8510606952292412e-06,
-0.047878689432542254